// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {vault} from '../models';

export function Bootstrap():Promise<main.BootstrapState>;

export function CopySecret(arg1:string):Promise<void>;

export function CopyText(arg1:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:string):Promise<main.BootstrapState>;

export function DeleteSecret(arg1:string):Promise<void>;

export function DeleteShortcut(arg1:string):Promise<void>;

export function FrontendLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FrontendReady():Promise<void>;

export function HideWindow():Promise<void>;

export function InsertText(arg1:string):Promise<string>;

export function ListSecrets():Promise<Array<vault.SecretMeta>>;

export function ListShortcuts():Promise<Array<vault.Shortcut>>;

export function LockProfile():Promise<main.BootstrapState>;

export function OpenCompact():Promise<void>;

export function OpenManager():Promise<void>;

export function Quit():Promise<void>;

export function ReloadLibrary():Promise<main.BootstrapState>;

export function RenderEntry(arg1:string,arg2:Record<string, string>):Promise<string>;

export function RenderShortcut(arg1:string):Promise<string>;

export function SaveSecret(arg1:vault.Secret):Promise<vault.SecretMeta>;

export function SaveShortcut(arg1:vault.Shortcut,arg2:string):Promise<vault.Shortcut>;

export function SwitchProfile():Promise<main.BootstrapState>;

export function UnlockProfile(arg1:string,arg2:string):Promise<main.BootstrapState>;

export function UseShortcut(arg1:string):Promise<string>;
