// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CopySecret(arg1) {
  return window['go']['main']['App']['CopySecret'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function DeleteShortcut(arg1) {
  return window['go']['main']['App']['DeleteShortcut'](arg1);
}

export function FrontendLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['FrontendLog'](arg1, arg2, arg3);
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InsertText(arg1) {
  return window['go']['main']['App']['InsertText'](arg1);
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function ListShortcuts() {
  return window['go']['main']['App']['ListShortcuts']();
}

export function LockProfile() {
  return window['go']['main']['App']['LockProfile']();
}

export function OpenCompact() {
  return window['go']['main']['App']['OpenCompact']();
}

export function OpenManager() {
  return window['go']['main']['App']['OpenManager']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReloadLibrary() {
  return window['go']['main']['App']['ReloadLibrary']();
}

export function RenderEntry(arg1, arg2) {
  return window['go']['main']['App']['RenderEntry'](arg1, arg2);
}

export function RenderShortcut(arg1) {
  return window['go']['main']['App']['RenderShortcut'](arg1);
}

export function SaveSecret(arg1) {
  return window['go']['main']['App']['SaveSecret'](arg1);
}

export function SaveShortcut(arg1, arg2) {
  return window['go']['main']['App']['SaveShortcut'](arg1, arg2);
}

export function SwitchProfile() {
  return window['go']['main']['App']['SwitchProfile']();
}

export function UnlockProfile(arg1, arg2) {
  return window['go']['main']['App']['UnlockProfile'](arg1, arg2);
}

export function UseShortcut(arg1) {
  return window['go']['main']['App']['UseShortcut'](arg1);
}
